import React from 'react';
import { FileText, AlertTriangle, ShieldAlert, CheckCircle2 } from 'lucide-react';

export const TermsOfUse: React.FC = () => {
  return (
    <div className="space-y-6 max-w-4xl mx-auto px-1 sm:px-0 font-sans">
      {/* Editorial Page Header */}
      <div className="pb-5 border-b border-slate-200 dark:border-slate-800 space-y-2">
        <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-sm text-xs text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-700 bg-transparent">
          <FileText className="w-3.5 h-3.5 text-rose-800 dark:text-rose-400 shrink-0" />
          <span>Legal Terms</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-serif font-bold tracking-tight text-slate-900 dark:text-slate-100">
          Terms of Use & Disclaimer
        </h1>
        <p className="text-slate-600 dark:text-slate-400 text-xs sm:text-sm max-w-2xl leading-relaxed">
          Please read these terms before using the WCE CGPA to Percentage Converter.
        </p>
      </div>

      {/* Main Terms Box */}
      <div className="bg-white dark:bg-[#151921] rounded-md p-5 sm:p-7 border border-slate-200 dark:border-slate-800 space-y-6 text-slate-700 dark:text-slate-300 text-xs sm:text-sm leading-relaxed">
        
        {/* Term 1: Provided As Is */}
        <section className="space-y-2">
          <h2 className="text-base sm:text-lg font-serif font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
            <span>1. "As Is" Informational Purpose</span>
          </h2>
          <p>
            <strong>WCE CGPA to Percentage Converter</strong> is provided strictly on an <strong>"as is" and "as available" basis</strong> for convenience and informational reference purposes only. While every care has been taken to implement the exact published formulas from WCE's <i>Academic and Examination Rules and Regulations 2023-24</i>, no warranty or guarantee of absolute accuracy, completeness, or suitability for any specific official purpose is implied.
          </p>
        </section>

        {/* Term 2: Verification Requirement */}
        <section className="space-y-2 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-base sm:text-lg font-serif font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-rose-900 dark:text-rose-400 shrink-0" />
            <span>2. Official Verification Requirement</span>
          </h2>
          <p>
            This tool does not issue official transcripts or grade sheets. For any formal academic, job application, higher education admission, passport, visa, scholarship, or legal purpose, you must verify your results against your official grade card or confirm them directly with the <strong>WCE Examination Section</strong>.
          </p>
        </section>

        {/* Term 3: Limitation of Liability */}
        <section className="space-y-2 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-base sm:text-lg font-serif font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-rose-900 dark:text-rose-400 shrink-0" />
            <span>3. Limitation of Liability</span>
          </h2>
          <p>
            Under no circumstances shall the developer or site owner be held liable for any direct, indirect, incidental, consequential, or special damages or losses resulting from the use of, or inability to use, this application or any reliance placed upon calculations generated by it.
          </p>
        </section>

        {/* Term 4: Unofficial Status */}
        <section className="space-y-2 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-base sm:text-lg font-serif font-bold text-slate-900 dark:text-white">
            4. Unofficial Status Notice
          </h2>
          <p>
            This website is an independent student utility and is not affiliated with, endorsed by, or representative of Walchand College of Engineering, Sangli. All institution names are referenced solely for descriptive academic purposes.
          </p>
        </section>

      </div>
    </div>
  );
};
