import React from 'react';
import { FileText, AlertTriangle, ShieldAlert, CheckCircle2 } from 'lucide-react';

export const TermsOfUse: React.FC = () => {
  return (
    <div className="space-y-8 max-w-4xl mx-auto py-4">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 rounded-2xl p-6 sm:p-8 text-white shadow-xl">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-slate-700 text-slate-200 border border-slate-600 mb-3">
          <FileText className="w-3.5 h-3.5" />
          Legal Terms
        </div>
        <h1 className="text-2xl sm:text-3xl font-black tracking-tight">Terms of Use & Disclaimer</h1>
        <p className="text-slate-300 text-xs sm:text-sm mt-1">
          Please read these terms before using the WCE CGPA to Percent Calculator.
        </p>
      </div>

      {/* Main Terms Box */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 sm:p-8 border border-slate-200 dark:border-slate-800 shadow-md space-y-6 text-slate-700 dark:text-slate-300 text-xs sm:text-sm leading-relaxed">
        
        {/* Term 1: Provided As Is */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0" />
            1. "As Is" Informational Purpose
          </h2>
          <p>
            <strong>WCE CGPA to Percent Calculator</strong> is provided strictly on an <strong>"as is" and "as available" basis</strong> for convenience and informational reference purposes only. While every care has been taken to implement the exact published formulas from WCE's <i>Academic and Examination Rules and Regulations 2023-24</i>, no warranty or guarantee of absolute accuracy, completeness, or suitability for any specific official purpose is implied.
          </p>
        </section>

        {/* Term 2: Verification Requirement */}
        <section className="space-y-2 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" />
            2. Official Verification Requirement
          </h2>
          <p>
            This tool does not issue official transcripts or grade sheets. For any formal academic, job application, higher education admission, passport, visa, scholarship, or legal purpose, you must verify your results against your official grade card or confirm them directly with the <strong>WCE Examination Section</strong>.
          </p>
        </section>

        {/* Term 3: Limitation of Liability */}
        <section className="space-y-2 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-rose-500 shrink-0" />
            3. Limitation of Liability
          </h2>
          <p>
            Under no circumstances shall the developer or site owner be held liable for any direct, indirect, incidental, consequential, or special damages or losses resulting from the use of, or inability to use, this application or any reliance placed upon calculations generated by it.
          </p>
        </section>

        {/* Term 4: Unofficial Status */}
        <section className="space-y-2 pt-4 border-t border-slate-200 dark:border-slate-800">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            4. Unofficial Status Notice
          </h2>
          <p>
            This website is an independent student utility and is not affiliated with, endorsed by, or representative of Walchand College of Engineering, Sangli. All institution names are referenced solely for descriptive academic purposes.
          </p>
        </section>

      </div>
    </div>
  );
};
